Initial models controllers
JulsdL/EasySky pull request #1
Opened 2023-03-06 16:17 UTC by JulsdL

Added models:

- booking
- observation_planning
- post
- item
- celestial_body
- targets
- booking_item

Added controller:
- bookings
- observation_plannings
- posts

2023-03-06 16:29 UTC, Ffaustine commented on db/migrate/20230306160055_create_posts.rb
> +      t.text :photo
variable photo ?
On ne devrait pas plutôt utiliser has_one_photo_attached ?

2023-03-06 16:30 UTC, Ffaustine requested changes
Regarder ensemble si variable photo ou si on utilise has_one_photo_attached

2023-03-06 16:30 UTC, Ffaustine commented on db/migrate/20230306160521_create_celestial_bodies.rb
> +      t.text :photo
variable photo ?
On ne devrait pas plutôt utiliser has_one_photo_attached ?

2023-03-07 11:57 UTC, JulsdL commented on db/migrate/20230306160521_create_celestial_bodies.rb
> +      t.text :photo
C'est corrigé, j'ai ajouté un fichier de migration DeleteColumnPhotos

2023-03-07 12:30 UTC, Ffaustine approved these changes

2023-03-07 12:30 UTC, merged